BlogApp/urls.py
from django.urls import path
from BlogApp import views

app_name = 'BlogApp'

urlpatterns = [
    path('', views.blog, name='blog'),
    path('details/', views.blog_details, name='blog_details')
]

MainApp/urls.py
from django.urls import path
from MainApp import views

app_name = 'MainApp'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('search/', views.search, name='search'),
]

OrderApp/urls.py
from django.urls import path
from OrderApp import views

app_name = 'OrderApp'

urlpatterns = [
    path('cart/<int:id>/', views.add_to_cart, name='add_to_cart'),
    path('cart-details/', views.cart_details, name='cart-details'),
    path('cart-delete/<int:id>/', views.cart_delete, name='cart-delete'),
    path('checkout/', views.order_cart, name='checkout'),
]

ProductApp/urls.py
from django.urls import path
from ProductApp import views

app_name = 'ProductApp'

urlpatterns = [
    path('details/<int:id>/', views.product_single, name='singe-product'),
    path('category/<int:id>/<slug:slug>', views.category_product, name='category-product'),
    path('comment/<int:id>/', views.comment_add, name='comment'),
]

ProsiddhoBD/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('MainApp.urls')),
    path('product/', include('ProductApp.urls')),
    path('order/', include('OrderApp.urls')),
    path('user/', include('UserApp.urls')),
    path('blog/', include('BlogApp.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

UserApp/urls.py
from django.urls import path
from UserApp import views

app_name = 'UserApp'

urlpatterns = [
    path('register/', views.user_register, name='register'),
    path('login/', views.user_login, name='login'),
    path('profile/', views.user_profile, name='profile'),
    path('update/', views.user_update, name='user-update'),
    path('password/', views.password_change, name='password-change'),
    path('logout/', views.user_logout, name='logout'),
]

templates/cart-details.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
            <!-- Begin Li's Breadcrumb Area -->
            <div class="breadcrumb-area">
                <div class="container">
                    <div class="breadcrumb-content">
                        <ul>
                            <li><a href="{% url 'MainApp:home' %}">Home</a></li>
                            <li class="active">Shopping Cart</li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- Li's Breadcrumb Area End Here -->
    <div>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    </div>
            <!--Shopping Cart Area Strat-->
            <div class="Shopping-cart-area pt-60 pb-60">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <form action="#">
                                <div class="table-content table-responsive">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th class="li-product-remove">remove</th>
                                                <th class="li-product-thumbnail">images</th>
                                                <th class="cart-product-name">Product</th>
                                                <th class="li-product-price">Unit Price</th>
                                                <th class="li-product-quantity">Quantity</th>
                                                <th class="li-product-subtotal">Total</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for p in cart_product %}
                                            <tr>
                                                <td class="li-product-remove"><a href="{% url 'OrderApp:cart-delete' id=p.id %}"><i class="fa fa-times"></i></a></td>
                                                <td class="li-product-thumbnail"><a href="#"><img src="{{ p.product.imageurl }}" style="width: 100px; height: 100px;" alt="Li's Product Image"></a></td>
                                                <td class="li-product-name"><a href="#">{{ p.product.title }}</a></td>
                                                <td class="li-product-price"><span class="amount">${{ p.price }}</span></td>
                                                <td class="quantity">
                                                    <label>Quantity</label>
                                                    <div class="cart-plus-minus">
                                                        <input class="cart-plus-minus-box" value="{{ p.quantity }}" type="text">
                                                        <div class="dec qtybutton"><i class="fa fa-angle-down"></i></div>
                                                        <div class="inc qtybutton"><i class="fa fa-angle-up"></i></div>
                                                    </div>
                                                </td>
                                                <td class="product-subtotal"><span class="amount">${{ p.amount }}</span></td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                                <div class="row">
                                    <div class="col-12">
                                        <div class="coupon-all">
                                            <div class="coupon">
                                                <input id="coupon_code" class="input-text" name="coupon_code" value="" placeholder="Coupon code" type="text">
                                                <input class="button" name="apply_coupon" value="Apply coupon" type="submit">
                                            </div>
                                            <div class="coupon2">
                                                <input class="button" name="update_cart" value="Update cart" type="submit">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-5 ml-auto">
                                        <div class="cart-page-total">
                                            <h2>Cart totals</h2>
                                            <ul>
                                                <li>Subtotal <span>$130.00</span></li>
                                                <li>Total <span>${{ total_amount }}</span></li>
                                            </ul>
                                            <a href="{% url 'OrderApp:checkout' %}">Proceed to checkout</a>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!--Shopping Cart Area End-->
{% endblock body %}

templates/category-product.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="content-wraper pt-60 pb-60">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <!-- shop-top-bar start -->
                            <div class="shop-top-bar mt-30">
                                <div class="shop-bar-inner">
                                    <div class="product-view-mode">
                                        <!-- shop-item-filter-list start -->
                                        <ul class="nav shop-item-filter-list" role="tablist">
                                            <li class="active" role="presentation"><a aria-selected="true" class="active show" data-toggle="tab" role="tab" aria-controls="grid-view" href="#grid-view"><i class="fa fa-th"></i></a></li>
                                            <li role="presentation"><a data-toggle="tab" role="tab" aria-controls="list-view" href="#list-view"><i class="fa fa-th-list"></i></a></li>
                                        </ul>
                                        <!-- shop-item-filter-list end -->
                                    </div>
                                    <div class="toolbar-amount">
                                        <span>Showing 1 to 9 of 15</span>
                                    </div>
                                </div>
                                <!-- product-select-box start -->
                                <div class="product-select-box">
                                    <div class="product-short">
                                        <p>Sort By:</p>
                                        <select class="nice-select">
                                            <option value="trending">Relevance</option>
                                            <option value="sales">Name (A - Z)</option>
                                            <option value="sales">Name (Z - A)</option>
                                            <option value="rating">Price (Low &gt; High)</option>
                                            <option value="date">Rating (Lowest)</option>
                                            <option value="price-asc">Model (A - Z)</option>
                                            <option value="price-asc">Model (Z - A)</option>
                                        </select>
                                    </div>
                                </div>
                                <!-- product-select-box end -->
                            </div>
                            <!-- shop-top-bar end -->
                            <!-- shop-products-wrapper start -->
                            <div class="shop-products-wrapper">
                                <div class="tab-content">
                                    <div id="grid-view" class="tab-pane fade active show" role="tabpanel">
                                        <div class="product-area shop-product-area">
                                            <div class="row">
                                                {% for p in product_category %}
                                                <div class="col-lg-3 col-md-4 col-sm-6 mt-40">
                                                    <!-- single-product-wrap start -->
                                                    <div class="single-product-wrap">
                                                        <div class="product-image">
                                                            <a href="{% url 'ProductApp:singe-product' id=p.id %}">
                                                                <img src="{{ p.imageurl }}" alt="Li's Product Image">
                                                            </a>
                                                            <span class="sticker">New</span>
                                                        </div>
                                                        <div class="product_desc">
                                                            <div class="product_desc_info">
                                                                <div class="product-review">
                                                                    <h5 class="manufacturer">
                                                                        <a href="#">{{ p.category }}</a>
                                                                    </h5>
                                                                    <div class="rating-box">
                                                                        <ul class="rating">
                                                                            <li><i class="fa fa-star-o"></i></li>
                                                                            <li><i class="fa fa-star-o"></i></li>
                                                                            <li><i class="fa fa-star-o"></i></li>
                                                                            <li class="no-star"><i class="fa fa-star-o"></i></li>
                                                                            <li class="no-star"><i class="fa fa-star-o"></i></li>
                                                                        </ul>
                                                                    </div>
                                                                </div>
                                                                <h4><a class="product_name" href="{% url 'ProductApp:singe-product' id=p.id %}">{{ p.title }}</a></h4>
                                                                <div class="price-box">
                                                                    <span class="new-price">{{ p.new_price }}</span>
                                                                </div>
                                                            </div>
                                                            <div class="add-actions">
                                                                <ul class="add-actions-link">
                                                                    <li class="add-cart active"><a href="{% url 'OrderApp:add_to_cart' id=p.id %}">Add to cart</a></li>
                                                                    <li><a href="#" title="quick view" class="quick-view-btn" data-toggle="modal" data-target="#exampleModalCenter"><i class="fa fa-eye"></i></a></li>
                                                                    <li><a class="links-details" href="wishlist.html"><i class="fa fa-heart-o"></i></a></li>
                                                                </ul>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <!-- single-product-wrap end -->
                                                </div>
                                                {% endfor %}
                                            </div>
                                        </div>
                                    </div>
                                    <div id="list-view" class="tab-pane product-list-view fade" role="tabpanel">
                                        <div class="row">
                                            <div class="col">
                                                {% for p in product_category %}
                                                <div class="row product-layout-list">
                                                    <div class="col-lg-3 col-md-5 ">
                                                        <div class="product-image">
                                                            <a href="{% url 'ProductApp:singe-product' id=p.id %}">
                                                                <img src="{{ p.imageurl }}" alt="Li's Product Image">
                                                            </a>
                                                            <span class="sticker">New</span>
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-5 col-md-7">
                                                        <div class="product_desc">
                                                            <div class="product_desc_info">
                                                                <div class="product-review">
                                                                    <h5 class="manufacturer">
                                                                        <a href="product-details.html">{{ p.category }}</a>
                                                                    </h5>
                                                                    <div class="rating-box">
                                                                        <ul class="rating">
                                                                            <li><i class="fa fa-star-o"></i></li>
                                                                            <li><i class="fa fa-star-o"></i></li>
                                                                            <li><i class="fa fa-star-o"></i></li>
                                                                            <li class="no-star"><i class="fa fa-star-o"></i></li>
                                                                            <li class="no-star"><i class="fa fa-star-o"></i></li>
                                                                        </ul>
                                                                    </div>
                                                                </div>
                                                                <h4><a class="product_name" href="{% url 'ProductApp:singe-product' id=p.id %}">{{ p.title }}</a></h4>
                                                                <div class="price-box">
                                                                    <span class="new-price">{{ p.new_price }}</span>
                                                                </div>
                                                                <p>{{ p.details }}</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-4">
                                                        <div class="shop-add-action mb-xs-30">
                                                            <ul class="add-actions-link">
                                                                <li class="add-cart"><a href="{% url 'OrderApp:add_to_cart' id=p.id %}">Add to cart</a></li>
                                                                <li class="wishlist"><a href="wishlist.html"><i class="fa fa-heart-o"></i>Add to wishlist</a></li>
                                                                <li><a class="quick-view" data-toggle="modal" data-target="#exampleModalCenter" href="#"><i class="fa fa-eye"></i>Quick view</a></li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>
                                                {% endfor %}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="paginatoin-area">
                                        <div class="row">
                                            <div class="col-lg-6 col-md-6">
                                                <p>Showing 1-12 of 13 item(s)</p>
                                            </div>
                                            <div class="col-lg-6 col-md-6">
                                                <ul class="pagination-box">
                                                    <li><a href="#" class="Previous"><i class="fa fa-chevron-left"></i> Previous</a>
                                                    </li>
                                                    <li class="active"><a href="#">1</a></li>
                                                    <li><a href="#">2</a></li>
                                                    <li><a href="#">3</a></li>
                                                    <li>
                                                      <a href="#" class="Next"> Next <i class="fa fa-chevron-right"></i></a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- shop-products-wrapper end -->
                        </div>
                    </div>
                </div>
            </div>
{% endblock %}

templates/header.html
{% load static %}
<header class="li-header-4">
                <!-- Begin Header Middle Area -->
                <div class="header-middle pl-sm-0 pr-sm-0 pl-xs-0 pr-xs-0">
                    <div class="container">
                        <div class="row">
                            <!-- Begin Header Logo Area -->
                            <div class="col-lg-3">
                                <div class="logo pb-sm-30 pb-xs-30">
                                    <a href="{% url 'MainApp:home' %}">
                                        <img src="{% static '' %}images/menu/logo/header.png" alt="">
                                    </a>
                                </div>
                            </div>
                            <!-- Header Logo Area End Here -->
                            <!-- Begin Header Middle Right Area -->
                            <div class="col-lg-9 pl-0 ml-sm-15 ml-xs-15">
                                <!-- Begin Header Middle Searchbox Area -->
                                <form action="{% url 'MainApp:search' %}" class="hm-searchbox" method="POST">
                                {% csrf_token %}
                                    <select name="category" class="nice-select select-search-category">
                                        <option value="0">All</option>
                                        {% for p in category %}
                                        <option value="{{ p.id }}">{{ p.title }}</option>
                                        {% endfor %}
                                    </select>
                                    <input type="text" placeholder="Enter your search key ..." id="query" name="query">
                                    <button class="btn btn-secondary" type="submit"><i class="fa fa-search"></i></button>
                                </form>
                                <!-- Header Middle Searchbox Area End Here -->
                                <!-- Begin Header Middle Right Area -->
                                <div class="header-middle-right">
                                    <ul class="ht-menu">
                                        <!-- Begin Header Middle Wishlist Area -->
                                        <li class="btn btn-secondary">
                                            <div class="ht-setting-trigger"><span>Account</span></div>
                                            <div class="setting ht-setting">
                                            <ul class="ht-setting-list">
                                                {% if user.id is not None %}
                                                    <li><a href="{% url 'UserApp:profile' %}">Profile: {{ request.user.username }}</a></li>
                                                    <li><a href="{% url 'UserApp:logout' %}">Logout</a></li>
                                                {% else %}
                                                    <li><a href="{% url 'UserApp:login' %}">Login</a></li>
                                                    <li><a href="{% url 'UserApp:register' %}">Register</a></li>
                                                {% endif %}
                                            </ul>
                                            </div>
                                        </li>
                                        <!-- Header Middle Wishlist Area End Here -->
                                        <!-- Begin Header Mini Cart Area -->
                                        <li class="hm-minicart">
                                            <div class="hm-minicart-trigger">
                                                <span class="item-icon"></span>
                                                <span class="item-text">£{{ total_amount }}
                                                    <span class="cart-item-count">2</span>
                                                </span>
                                            </div>
                                            <span></span>
                                            <div class="minicart">
                                                <ul class="minicart-product-list">
                                                    {% for p in cart_product %}
                                                    <li>
                                                        <a class="minicart-product-image">
                                                            <img src="{{ p.product.imageurl }}" alt="cart products">
                                                        </a>
                                                        <div class="minicart-product-details">
                                                            <h6>{{ p.product.title }}</h6>
                                                            <span>£{{ p.price }} x {{ p.quantity }}</span>
                                                        </div>
                                                        <button class="close">
                                                            <a href="{% url 'OrderApp:cart-delete' id=p.id %}"><i class="fa fa-close"></i></a>
                                                        </button>
                                                    </li>
                                                    {% endfor %}
                                                </ul>
                                                <p class="minicart-total">SUBTOTAL: <span>£{{ total_amount }}</span></p>
                                                <div class="minicart-button">
                                                    <a href="{% url 'OrderApp:cart-details' %}" class="btn btn-secondary li-button-fullwidth li-button-sm">
                                                        <span>View Full Cart</span>
                                                    </a>
                                                    <br>
                                                    <a href="{% url 'OrderApp:checkout' %}" class="btn btn-secondary li-button-fullwidth li-button-sm">
                                                        <span>Checkout</span>
                                                    </a>
                                                </div>
                                            </div>
                                        </li>
                                        <!-- Header Mini Cart Area End Here -->
                                    </ul>
                                </div>
                                <!-- Header Middle Right Area End Here -->
                            </div>
                            <!-- Header Middle Right Area End Here -->
                        </div>
                    </div>
                </div>
                <!-- Header Middle Area End Here -->
                <!-- Begin Header Bottom Area -->
                <div class="header-bottom header-sticky stick d-none d-lg-block d-xl-block">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-12">
                               <!-- Begin Header Bottom Menu Area -->
                               <div class="hb-menu">
                                   <nav>
                                       <ul>
                                           <li><a href="{% url 'MainApp:home' %}">Home</a></li>
                                           <li class="dropdown-holder"><a href="#">Shop</a>
                                               <ul class="hb-dropdown">
                                                   {% for p in category %}
                                                   <li><a href="{% url 'ProductApp:category-product' id=p.id slug=p.slug %}">{{ p.title }}</a>
                                                   </li>
                                                   {% endfor %}
                                               </ul>
                                           </li>
                                           <li><a href="{% url 'BlogApp:blog' %}">Blog</a>
                                           </li>
                                           <li class="megamenu-static-holder"><a href="index.html">Services</a>
                                           </li>
                                           <li><a href="{% url 'MainApp:about' %}">About Us</a></li>
                                           <li><a href="{% url 'MainApp:contact' %}">Contact</a></li>
                                       </ul>
                                   </nav>
                               </div>
                               <!-- Header Bottom Menu Area End Here -->
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Header Bottom Area End Here -->
                <!-- Begin Mobile Menu Area -->
                <div class="mobile-menu-area mobile-menu-area-4 d-lg-none d-xl-none col-12">
                    <div class="container">
                        <div class="row">
                            <div class="mobile-menu">
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Mobile Menu Area End Here -->
            </header>

templates/user-panel.html
        <div class="aside">
            <ul class="list-links">
                <li><a href="{% url 'UserApp:profile' %}">User Profile</a></li>
                <li><a href="">My Orders</a></li>
                <li><a href="">My Order Product</a></li>
                <li><a href="">My Comments</a></li>
                <li><a href="">My Favorits</a></li>
                <li><a href="">My Products</a></li>
                <li><a href="{% url 'UserApp:logout' %}">Logout</a></li>
            </ul>
        </div>